openapi: 3.0.3
info:
  title: HTTP API for pdjr-skplugin-alarm-manager
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    [pdjr-skplugin-alarm-manager](https://github.com/pdjr-signalk/pdjr-skplugin-alarm-manager)
    is a plugin for the
    [Signal K node server](https://github.com/SignalK/signalk-server).

    A Signal K server hosting the plugin will present this API under
    the root https://*server_ip*:*server_port*/plugins/alarm-manager.
externalDocs:
  description: Plugin README document
  url: https://github.com/pdjr-signalk/pdjr-skplugin-alarm-manager#readme 
paths:
  /digest:
    get:
      description: |
        Get a digest of all active alarm notifications.
      responses:
        200:
          description: |
            Success.
            The response body is an object with the paths of alarm
            notifications as property names and property values which
            include notification and suppression details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/digest"
        500:
          description: |
            Error.
            The server was unable to service the request.
  /outputs:
    get:
      description: |
        Get the state of all configured outputs.
      responses:
        200:
          description: |
            Success.
            The response body is an object containing the state of all alarm outputs.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/outputs"
        500:
          description: |
            Error.
            The server was unable to service the request.
  /outputs/{name}:
    get:
      description: |
        Get the current state of the output specified by {name}.
      parameters:
      - name: name
        in: path
        description: |
          Identifier of the output channel whose state is required.
        required: true
        schema:
          $ref: "#/components/schemas/name"
      responses:
        200:
          description: |
            Success.
            The response body contains the value 1 to indicate that
            the output is ON, or 0 to indicate that the output is OFF.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/state"
        404:
          description: |
            Error.
            The request was invalid (bad or missing output {name}).
        500:
          description: |
            Error.
            The server was unable to service the request.
  /suppress/{name}:
    patch:
      description: |
        Suppress output on output channel {name}.
      parameters:
      - name: name
        in: path
        description: |
          Identifier of the output channel which should be suppressed.
        required: true
        schema:
          $ref: "#/components/schemas/name"
      responses:
        200:
          description: |
            Success.
            Output channel {name} has been suppressed.
        404:
          description: |
            Error.
            The request was invalid (bad or missing output {name}).
        500:
          description: |
            Error.
            The server was unable to service the request.
components:
  schemas:
    name:
      description: |
        Name of an alarm output channel as defined in the alarm-manager
        configuration.
      example: "annunciator"
      type: string
    state:
      description: |
        State of an alarm output channel expressed as an integer where
        0 says OFF, 1 says ON.
      example: 0
      type: number
      minimum: 0
      maximum: 1
    outputs:
      description: |
        Object summarising the state of all alarm outputs.
        Each property name is the name of a configured output channel
        with a value indication the channel state.
      example:
        { "beacon": 1, "annunciator": 0 }
      type: object
      additionalProperties:
        $ref: "#/components/schemas/state"
    digest:
      description: |
        Object containing a collection of active alarm notifications
        under plugin control.
        Each property name is a Signal K key on which an alarm
        notification has been raised and to which the associated
        property value relates.
      type: object
      additionalProperties:
        type: object
        properties:
          notification: 
            properties:
              state:
                type: string
                description: Alarm state of the notification.
              method:
                type: array
                items:
                  type: string
              message:
                type: string
              id:
                type: string
          suppressedOutputs:
            type: array
            items:
              $ref: "#/components/schemas/name"
