openapi: 3.0.3
info:
  title: alarm-manager API
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    [pdjr-skplugin-alarm-manager](https://github.com/pdjr-signalk/pdjr-skplugin-alarm-manager)
    is a plugin for the
    [Signal K node server](https://github.com/SignalK/signalk-server).

    A Signal K server hosting the plugin will present this API under
    the root https://*server_ip*:*server_port*/plugins/alarm-manager.
externalDocs:
  description: Plugin README document
  url: https://github.com/pdjr-signalk/pdjr-skplugin-alarm-manager#readme 
paths:
  /keys:
    get:
      description: |
        Get a digest of all Signal K keys which are being monitored for
        alarm activity (i.e. all keys where the associated metadata
        includes some zone definitions).
      responses:
        200:
          description: |
            Success.
            The response body is an array containing the keys of all
            currently monitored data items.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        500:
          description: |
            Error.
            The server was unable to service the request.       
  /digest:
    get:
      description: |
        Get a digest of all active alarm notifications.
      responses:
        200:
          description: |
            Success.
            The response body is an object with the paths of alarm
            notifications as property names and property values which
            include notification and suppression details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  additionalProperties:
                    type: object
                    properties:
                      notification: 
                        properties:
                          state:
                            type: string
                            description: Alarm state of the notification.
                          method:
                            type: array
                            items:
                              type: string
                          message:
                            type: string
                          id:
                            type: string
                      suppressedOutputs:
                        type: array
                        items:
                          type: string
        500:
          description: |
            Error.
            The server was unable to service the request.
  /outputs:
    get:
      description: |
        Get the state of all configured outputs.
      responses:
        200:
          description: |
            Success.
            The response body is an object with the names of alarm
            output channels as property names and the current channel
            state a the property value.
          content:
            application/json:
              schema:
                type: object
                properties:
                  additionalProperties:
                    type: number
                    minimum: 0
                    maximum: 1
        500:
          description: |
            Error.
            The server was unable to service the request.
  /output/{output}:
    get:
      description: |
        Get the current state of the output specified by {name}.
      parameters:
      - output:
        name: output
        in: path
        description: |
          Name of the output channel whose state is required.
        required: true
        schema:
          type: string
      responses:
        200:
          description: |
            Success.
            The response body contains the value 1 to indicate that
            the output is ON, or 0 to indicate that the output is OFF.
          content:
            application/json:
              schema:
                type: number
                minimum: 0
                maximum: 1
        404:
          description: |
            Error.
            The request was invalid (bad or missing output channel name).
        500:
          description: |
            Error.
            The server was unable to service the request.
  /suppress/{output}:
    patch:
      description: |
        Suppress output on output channel {name}.
      parameters:
      - output:
        name: output
        in: path
        description: |
          Identifier of the output channel which should be suppressed.
        required: true
        schema:
          type: string
      responses:
        200:
          description: |
            Success.
            Output channel has been suppressed.
        404:
          description: |
            Error.
            The request was invalid (bad or missing output channel name).
        500:
          description: |
            Error.
            The server was unable to service the request.
